# Generated by cpp4r: do not edit by hand

sendWSMessage <- function(conn, binary, message) {
	invisible(.Call(`_httpserver_sendWSMessage`, conn, binary, message))
}

closeWS <- function(conn, code, reason) {
	invisible(.Call(`_httpserver_closeWS`, conn, code, reason))
}

makeTcpServer <- function(host, port, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet) {
	.Call(`_httpserver_makeTcpServer`, host, port, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet)
}

makePipeServer <- function(name, mask, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet) {
	.Call(`_httpserver_makePipeServer`, name, mask, onHeaders, onBodyData, onRequest, onWSOpen, onWSMessage, onWSClose, staticPaths, staticPathOptions, quiet)
}

stopServer_ <- function(handle) {
	invisible(.Call(`_httpserver_stopServer_`, handle))
}

getStaticPaths_ <- function(handle) {
	.Call(`_httpserver_getStaticPaths_`, handle)
}

setStaticPaths_ <- function(handle, sp) {
	.Call(`_httpserver_setStaticPaths_`, handle, sp)
}

removeStaticPaths_ <- function(handle, paths) {
	.Call(`_httpserver_removeStaticPaths_`, handle, paths)
}

getStaticPathOptions_ <- function(handle) {
	.Call(`_httpserver_getStaticPathOptions_`, handle)
}

setStaticPathOptions_ <- function(handle, opts) {
	.Call(`_httpserver_setStaticPathOptions_`, handle, opts)
}

base64encode <- function(x) {
	.Call(`_httpserver_base64encode`, x)
}

#' @title URI encoding/decoding
#' 
#' @description Encodes/decodes strings using URI encoding/decoding in the same way that web
#'  browsers do. The precise behaviors of these functions can be found at developer.mozilla.org:
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI}{encodeURI},
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent}{encodeURIComponent},
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI}{decodeURI},
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent}{decodeURIComponent}
#' 
#'  Intended as a faster replacement for [utils::URLencode()] and [utils::URLdecode()].
#'  encodeURI differs from encodeURIComponent in that the former will not encode
#'  reserved characters: \code{;,/?:@@&=+$}
#' 
#'  decodeURI differs from decodeURIComponent in that it will refuse to decode
#'  encoded sequences that decode to a reserved character. (If in doubt, use
#'  decodeURIComponent.)
#' 
#'  For \code{encodeURI} and \code{encodeURIComponent}, input strings will be
#'  converted to UTF-8 before URL-encoding.
#' 
#' @param value Character vector to be encoded or decoded.
#' 
#' @return Encoded or decoded character vector of the same length as the
#'  input value. \code{decodeURI} and \code{decodeURIComponent} will return
#'  strings that are UTF-8 encoded.
#' 
#' @export
encodeURI <- function(value) {
	.Call(`_httpserver_encodeURI`, value)
}

#' @rdname encodeURI
#' @export
encodeURIComponent <- function(value) {
	.Call(`_httpserver_encodeURIComponent`, value)
}

#' @rdname encodeURI
#' @export
decodeURI <- function(value) {
	.Call(`_httpserver_decodeURI`, value)
}

#' @rdname encodeURI
#' @export
decodeURIComponent <- function(value) {
	.Call(`_httpserver_decodeURIComponent`, value)
}

#' @title Check whether an address is IPv4 or IPv6
#' 
#' @description Given an IP address, this checks whether it is an IPv4 or IPv6 address.
#' 
#' @param ip A single string representing an IP address.
#' 
#' @return For IPv4 addresses, \code{4}; for IPv6 addresses, \code{6}. If the address is neither, \code{-1}.
#' 
#' @examples
#'  ipFamily("127.0.0.1")   # 4
#'  ipFamily("500.0.0.500") # -1
#'  ipFamily("500.0.0.500") # -1
#' 
#'  ipFamily("::")          # 6
#'  ipFamily("::1")         # 6
#'  ipFamily("fe80::1ff:fe23:4567:890a") # 6
#' 
#' @export
ipFamily <- function(ip) {
	.Call(`_httpserver_ipFamily`, ip)
}

invokeCppCallback <- function(data, callback_xptr) {
	invisible(.Call(`_httpserver_invokeCppCallback`, data, callback_xptr))
}

#' @title Apply the value of .Random.seed to R's internal RNG state
#' 
#' @description This function is needed in unusual cases where a C++ function calls
#'  an R function which sets the value of \code{.Random.seed}. This function
#'  should be called at the end of the R function to ensure that the new value
#'  \code{.Random.seed} is preserved.
#' 
#' @keywords internal
#' 
#' @export
getRNGState <- function() {
	invisible(.Call(`_httpserver_getRNGState`))
}

wsconn_address <- function(external_ptr) {
	.Call(`_httpserver_wsconn_address`, external_ptr)
}

log_level <- function(level) {
	.Call(`_httpserver_log_level`, level)
}
