# Generated by cpp4r: do not edit by hand

log_level <- function(level) {
	.Call(`_httpserver_log_level`, level)
}

send_ws_message <- function(conn, binary, message) {
	invisible(.Call(`_httpserver_send_ws_message`, conn, binary, message))
}

close_ws <- function(conn, code, reason) {
	invisible(.Call(`_httpserver_close_ws`, conn, code, reason))
}

make_tcp_server <- function(host, port, on_headers, on_body_data, on_request, on_wsopen, on_wsmessage, on_wsclose, static_paths, static_path_options, quiet) {
	.Call(`_httpserver_make_tcp_server`, host, port, on_headers, on_body_data, on_request, on_wsopen, on_wsmessage, on_wsclose, static_paths, static_path_options, quiet)
}

make_pipe_server <- function(name, mask, on_headers, on_body_data, on_request, on_wsopen, on_wsmessage, on_wsclose, static_paths, static_path_options, quiet) {
	.Call(`_httpserver_make_pipe_server`, name, mask, on_headers, on_body_data, on_request, on_wsopen, on_wsmessage, on_wsclose, static_paths, static_path_options, quiet)
}

stop_server_ <- function(handle) {
	invisible(.Call(`_httpserver_stop_server_`, handle))
}

get_static_paths_ <- function(handle) {
	.Call(`_httpserver_get_static_paths_`, handle)
}

set_static_paths_ <- function(handle, sp) {
	.Call(`_httpserver_set_static_paths_`, handle, sp)
}

remove_static_paths_ <- function(handle, paths) {
	.Call(`_httpserver_remove_static_paths_`, handle, paths)
}

get_static_path_options_ <- function(handle) {
	.Call(`_httpserver_get_static_path_options_`, handle)
}

set_static_path_options_ <- function(handle, opts) {
	.Call(`_httpserver_set_static_path_options_`, handle, opts)
}

base64_encode <- function(x) {
	.Call(`_httpserver_base64_encode`, x)
}

#' @title URI encoding/decoding
#' 
#' @description Encodes/decodes strings using URI encoding/decoding in the same way that web
#'  browsers do. The precise behaviors of these functions can be found at developer.mozilla.org:
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encode_uri}{encode_uri},
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encode_uri_component}{encode_uri_component},
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decode_uri}{decode_uri},
#'  \href{https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decode_uricomponent}{decode_uricomponent}
#' 
#'  Intended as a faster replacement for [utils::URLencode()] and [utils::URLdecode()].
#'  encode_uri differs from encode_uri_component in that the former will not encode
#'  reserved characters: \code{;,/?:@@&=+$}
#' 
#'  decode_uri differs from decode_uricomponent in that it will refuse to decode
#'  encoded sequences that decode to a reserved character. (If in doubt, use
#'  decode_uricomponent.)
#' 
#'  For \code{encode_uri} and \code{encode_uri_component}, input strings will be
#'  converted to UTF-8 before URL-encoding.
#' 
#' @param value Character vector to be encoded or decoded.
#' 
#' @return Encoded or decoded character vector of the same length as the
#'  input value. \code{decode_uri} and \code{decode_uricomponent} will return
#'  strings that are UTF-8 encoded.
#' 
#' @export
encode_uri <- function(value) {
	.Call(`_httpserver_encode_uri`, value)
}

#' @rdname encode_uri
#' @export
encode_uri_component <- function(value) {
	.Call(`_httpserver_encode_uri_component`, value)
}

#' @rdname encode_uri
#' @export
decode_uri <- function(value) {
	.Call(`_httpserver_decode_uri`, value)
}

#' @rdname encode_uri
#' @export
decode_uricomponent <- function(value) {
	.Call(`_httpserver_decode_uricomponent`, value)
}

#' @title Check whether an address is IPv4 or IPv6
#' 
#' @description Given an IP address, this checks whether it is an IPv4 or IPv6 address.
#' 
#' @param ip A single string representing an IP address.
#' 
#' @return For IPv4 addresses, \code{4}; for IPv6 addresses, \code{6}. If the address is neither, \code{-1}.
#' 
#' @examples
#'  ip_family("127.0.0.1")   # 4
#'  ip_family("500.0.0.500") # -1
#'  ip_family("500.0.0.500") # -1
#' 
#'  ip_family("::")          # 6
#'  ip_family("::1")         # 6
#'  ip_family("fe80::1ff:fe23:4567:890a") # 6
#' 
#' @export
ip_family <- function(ip) {
	.Call(`_httpserver_ip_family`, ip)
}

invoke_cpp_callback <- function(data, callback_xptr) {
	invisible(.Call(`_httpserver_invoke_cpp_callback`, data, callback_xptr))
}

#' @title Apply the value of .Random.seed to R's internal RNG state
#' 
#' @description This function is needed in unusual cases where a C++ function calls
#'  an R function which sets the value of \code{.Random.seed}. This function
#'  should be called at the end of the R function to ensure that the new value
#'  \code{.Random.seed} is preserved.
#' 
#' @export
getRNGState <- function() {
	invisible(.Call(`_httpserver_getRNGState`))
}

wsconn_address <- function(external_ptr) {
	.Call(`_httpserver_wsconn_address`, external_ptr)
}
